package about;

import javafx.fxml.FXML;

import javafx.scene.control.Button;
import javafx.scene.control.TextArea;
import javafx.stage.Stage;


import javafx.event.ActionEvent;

public class AboutController {
	@FXML
	private Button Button_OK;

	@FXML
    private TextArea TextArea_VersionLog;
	
	public AboutController() {
		System.out.print("init");
	}
	
	public void initialize() {
		String s = 
				"第二次上传推送" +
			"2019-09-19 xuxingxing2018 第一次建立github.\r\n";
		TextArea_VersionLog.setText(s);
		//System.out.println(s);
	}
	
	// Event Listener on Button[#Button_OK].onAction
	@FXML
	public void Button_OK_MouseClicked(ActionEvent event) {
		// TODO Autogenerated
		Stage stage = (Stage)Button_OK.getScene().getWindow();
		stage.close();
	}
	
	
}
